name: 'Balena CLI (Nebra fork)'
branding:
  color: "yellow"
  icon: "upload-cloud"
description: 'Continuously deliver your IoT applications to BalenaCloud'
inputs:
  application_path:
    description: "Optional. Provide a subfolder path to your BalenaCloud application, example: ./balena-wpe"
    required: false
    default: "."
  balena_api_token:
    description: 'BalenaCloud API Key'
    required: true
  balena_command:
    description: "The command to execute with balena"
    required: true
  balena_secrets:
    description: "Optional contents of a balena secrets.json file"
    required: false
  nebraos_cloud:
    description: "Has to be used if NebraOS cloud will be used as target"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.balena_command }}
